# Download & install dependencies, run build scripts, you name it - tasks Gitpod takes care of before you start a new development environment 
# so you don’t have to wait for any of that. With prebuilds enabled for your project, Gitpod runs the before, init and prebuild commands 
# in your `.gitpod.yml` file every time code is pushed to your repository. The resulting snapshot of the development environment is called a prebuilt workspace.
# When anyone starts a new workspace, all Gitpod needs to do is load the prebuilt workspace. 
# Since the heavy-lifting happened during the prebuild phase, the workspace starts up quickly, allowing you to start your work right away.

# Setup for GitHub.com -- Install the app here: https://github.com/apps/gitpod-io

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

tasks:
  - name: Depends_install
  - before: |
      curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh \
        --output /workspace/Mambaforge3-Linux-x86_64.sh
      bash /workspace/Mambaforge3-Linux-x86_64.sh -b -p /workspace/miniforge3
      echo "PATH="/workspace/miniforge3/bin:$PATH"" >> ${HOME}/.bashrc
      rm /workspace/Mambaforge3-Linux-x86_64.sh
      /workspace/miniforge3/bin/conda init bash
      source ~/.bashrc
      conda env create --file environment.yml -n dbooth
  - init: |
      echo 'Init script' # runs during prebuild
      conda activate dbooth
    command: conda -V && python -V && python -m ipykernel install --user --name=dbooth

## Currently 'dbooth' chooses to be a python 3.8 environment

# NOTE: Plan for now is just to work in the conda base environment - could use a one or two other
#       conda envs if warranted -- this disposable Gitpod.io infrastructure sort of takes care
#       of not getting too distracted with Docker / virtualenvs / conda envs.


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/

ports:
  - port: 8888
    onOpen: notify

# VS Code extensions to install

vscode:
  extensions:
    - "eamodio.gitlens"
