# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

tasks:
  - name: Depends_install
  - before: |
      curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh \
        --output /workspace/Mambaforge3-Linux-x86_64.sh
      bash /workspace/Mambaforge3-Linux-x86_64.sh -b -p /workspace/miniforge3
      echo "PATH="/workspace/miniforge3/bin:$PATH"" >> ${HOME}/.bashrc
      rm /workspace/Mambaforge3-Linux-x86_64.sh
      /workspace/miniforge3/bin/conda init bash
      source ~/.bashrc
      conda env create --file environment.yml -n dbooth
  - init: |
      echo 'Init script' # runs during prebuild
      conda activate dbooth
    command: conda -V && python -V && python -m ipykernel install --user --name=dbooth

## Currently 'dbooth' chooses to be a python 3.8 environment

# NOTE: Plan for now is just to work in the conda base environment - could use a one or two other
#       conda envs if warranted -- this disposable Gitpod.io infrastructure sort of takes care
#       of not getting too distracted with Docker / virtualenvs / conda envs.


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/

ports:
  - port: 8888
    onOpen: notify

# VS Code extensions to install

vscode:
  extensions:
    - "eamodio.gitlens"
